# ------ Theme Settings ------
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# ------ Site Settings ------
title: Mortad3lla
description: Personal webpage of Mortad3lla. Research, publications, and projects.

