# ------ Theme Settings ------
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# ------ Site Settings ------
title: mortadella
description: Personal webpage of a mathematics enthusiast. Research, publications, and projects.

